-- +goose Up
-- Google Sign-In support. google_sub/email/avatar_url stay nullable at the
-- column level (not NOT NULL) because the seeded pre-auth user
-- (00000000-0000-0000-0000-000000000001, see 00002_seed.sql) has none of
-- these yet — it's claimed by whichever Google account logs in first (see
-- AuthService), at which point it gets real values like any other user.
-- Postgres UNIQUE allows multiple NULLs, so this doesn't weaken the
-- uniqueness guarantee for rows that do have a value.
ALTER TABLE users ADD COLUMN google_sub text UNIQUE;
ALTER TABLE users ADD COLUMN email_verified boolean NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN avatar_url text;
ALTER TABLE users ADD CONSTRAINT users_email_key UNIQUE (email);

-- Session tokens are opaque, cryptographically random values generated by
-- the backend (see SessionsRepo.Create) — the "token" column IS the cookie
-- value, so no separate id/lookup indirection is needed.
CREATE TABLE sessions (
    token text PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_sessions_user ON sessions (user_id);

-- +goose Down
DROP TABLE IF EXISTS sessions;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_key;
ALTER TABLE users DROP COLUMN IF EXISTS avatar_url;
ALTER TABLE users DROP COLUMN IF EXISTS email_verified;
ALTER TABLE users DROP COLUMN IF EXISTS google_sub;
